### ISSUE TITLE
Work-around for Scala.js + IntelliJ Split-Implementation Bug?

### ISSUE THREAD

**Issue by ryan-richt** [wiringbits/scala-webapp-template#244]
Howdy folks! Stumbled upon this super cool repo from one of your reddit posts. Given the set of tools you have assembled here (Scala.js + sbt-crossproject + IntelliJ), I'd expect you've maybe run into this loooooong standing IntelliJ bug with this setup:

https://youtrack.jetbrains.com/issue/SCL-18334/sbt-crossproject-shared-sources-do-not-see-jvm-js-sources

Any chance that you folks have found a work-around here or elsewhere? I guess I was hoping for, a work-around better than the solution in comments here:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/206633785-scala-js-IDEA-does-not-find-individual-JS-and-JVM-implementations-of-an-object-sbt-compile-sbt-test-works-fine

Thank you so much

**Comment by AlexITC** [comment]
I just tried creating a trait at the `shared` module with an implementation at the `jvm` and `js` modules, it works fine to me, this is my setup:

![Screenshot from 2022-04-26 17-28-20](https://user-images.githubusercontent.com/4218436/165409079-5dd8aa18-2227-4bd8-b6c4-a12f74032bc8.png)
