### ISSUE TITLE
Reloading some pages get the user redirected to the home page

### ISSUE THREAD

**Issue by AlexITC** [wiringbits/scala-webapp-template#264]
For example, go to `http://localhost:8080/me`, reload the page, you will be redirected to the home page.

We should keep the user at the same page instead.

**Comment by DrewRoby** [comment]
Appears fixed after update

**Comment by AlexITC** [comment]
Thanks for checking, I'll double check soon.

**Comment by AlexITC** [comment]
I just verified that this is not an issue anymore, thanks for raising this.
